<a href="https://colab.research.google.com/github/BhekiMabheka/Data_Driven_Competions/blob/master/Untitled1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
## Data Wrangling Packages
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

## Machine Learning and Sci-kit learn packages
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split
from sklearn.ensemble import GradientBoostingRegressor, RandomForestRegressor, ExtraTreesRegressor
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error

train_feats = pd.read_csv("https://raw.githubusercontent.com/BhekiMabheka/Data/master/Training_Data_Feeats.csv")
print(train_feats.shape)

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm

(1456, 24)

In [2]:
train_feats.head()

  city  year  ...  station_min_temp_c station_precip_mm
0   sj  1990  ...                20.0              16.0
1   sj  1990  ...                22.2               8.6
2   sj  1990  ...                22.8              41.4
3   sj  1990  ...                23.3               4.0
4   sj  1990  ...                23.9               5.8

[5 rows x 24 columns]